<?php
class AdmAction extends CommonAction {

    /**
     * 管理员所有操作都必须检验是否已经登录并且用户是否有权限,只有大于2以上才算是管理员
     * @return bool
     */
    protected function isLog() {
        return parent::isLog() && $this->isAdm(); // TODO: Change the autogenerated stub
    }

    /**
     * 重写父类 throwUnlogErr 方法 如果没有登陆
     */
    protected function throwUnlogErr() {
        $this->ajaxReturn(null,'您没有权限执行该操作',false); // TODO: Change the autogenerated stub
    }

    /**
     * $_POS['id'],目前不需要
     * 而且需要扫描二维码
     */
    public function forbidUser() {
        $M = M('User');
        $status =
            $M->
            where(array(M('User')->getPk()=>array('eq',(int)$_POST['id'])))->
            save(array('status'=>0));
        $this->ajaxReturn(0,0,$status);
    }

    /**
     * $_POS['id']
     */
    public function blockComment() {
        $M = M('Comment');
        $status =
            $M->
            where(array($M->getPk()=>array('eq',"'".(int)$_POST['id']."''")))->
            save(array('status'=>0));
        $this->ajaxReturn(0,$status? '屏蔽成功' : '屏蔽失败',$status);
    }

    public function showComment() {
        $M = M('Comment');
        $status =
            $M->
            where(array($M->getPk()=>array('eq',"'".(int)$_POST['id']."''")))->
            save(array('status'=>1));
        $this->ajaxReturn(0,$status? '恢复成功' : '恢复失败',$status);
    }
}