<?php
class AdmAction extends CommonAction {

    /**
     * 管理员所有操作都必须检验是否已经登录并且用户是否有权限,只有大于2以上才算是管理员
     * @return bool
     */
    protected function isLog() {
        return parent::isLog() && $this->isAdm(); // TODO: Change the autogenerated stub
    }

    /**
     * 重写父类 throwUnlogErr 方法 如果没有登陆
     */
    protected function throwUnlogErr() {
        $this->ajaxReturn(null,'您没有权限执行该操作',false); // TODO: Change the autogenerated stub
    }

    /**
     * 记录用户真正的uid
     * @param $uid
     */
    protected function setRealId($uid) {
        $_SESSION['real'] = $uid;
    }

    /**
     * 返回用户真的uid
     * @return int
     */
    protected function getRealId() {
        return (int)$_SESSION['real'];
    }

    /**
     * $_POS['id'],目前不需要
     * 而且需要扫描二维码
     */
    public function forbidUser() {
        $M = M('User');
        $status =
            $M->
            where(array(M('User')->getPk()=>array('eq',(int)$_POST['id'])))->
            save(array('status'=>0));
        $this->ajaxReturn(0,0,$status);
    }

    /**
     * 屏蔽评论
     * $_POS['id']
     */
    public function blockComment() {
        $this->setCommentStatus(0);
    }

    /**
     * 取消评论的屏蔽效果
     * $_POS['id']
     */
    public function showComment() {
        $this->setCommentStatus(1);
    }

    /**
     * 推荐评论
     * $_POS['id']
     */
    public function recommendComment() {
        $this->setCommentRecmmd(1);
    }

    /**
     * 取消推荐评论
     * $_POS['id']
     */
    public function recommendCancel() {
        $this->setCommentRecmmd(0);
    }

    /**
     * 设置评论状态
     * @param $s
     */
    protected function setCommentStatus($s) {
        $M = M('Comment');
        $status =
            $M->
            where( $M->getPk().'=\''.(int)$_POST['id'].'\'' )->
            save(array('status'=>$s));
        $this->ajaxReturn($_POST,$status? '操作成功' : '操作失败'.$M->getDbError(),$status);

    }

    /**
     * 设置评论状态
     * @param $r
     */
    protected function setCommentRecmmd($r) {
        $M = M('Comment');
        $status =
            $M->
            where( $M->getPk().'=\''.(int)$_POST['id'].'\'' )->
            save(array('recmmd'=>$r));
        $this->ajaxReturn($_POST,$status? '操作成功' : '操作失败'.$M->getDbError(),$status);

    }
}